/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface LplLanding {
    }
    interface LplPrivacy {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLplLandingElement extends Components.LplLanding, HTMLStencilElement {
    }
    var HTMLLplLandingElement: {
        prototype: HTMLLplLandingElement;
        new (): HTMLLplLandingElement;
    };
    interface HTMLLplPrivacyElement extends Components.LplPrivacy, HTMLStencilElement {
    }
    var HTMLLplPrivacyElement: {
        prototype: HTMLLplPrivacyElement;
        new (): HTMLLplPrivacyElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "lpl-landing": HTMLLplLandingElement;
        "lpl-privacy": HTMLLplPrivacyElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface LplLanding {
    }
    interface LplPrivacy {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "lpl-landing": LplLanding;
        "lpl-privacy": LplPrivacy;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "lpl-landing": LocalJSX.LplLanding & JSXBase.HTMLAttributes<HTMLLplLandingElement>;
            "lpl-privacy": LocalJSX.LplPrivacy & JSXBase.HTMLAttributes<HTMLLplPrivacyElement>;
        }
    }
}
